### ISSUE TITLE
Roadmap for future development

### ISSUE THREAD

**Issue by klkeys** [klkeys/IHT.jl#1]
IHT.jl implements iterative hard thresholding in a (decently) efficient manner. It provides crossvalidation routines to select the best sparsity level among a vector of possible levels. Finally, it interfaces with PLINK.jl to enable GWAS analysis.

Nonetheless, the facilities in IHT.jl are still somewhat limited and ripe for improvements and extensions. Among the proposed improvements are:
- [ ] fix the logistic regression code, which currently suffers from multiple instabilities. References for logistic regression with IHT are [BRB13](http://arxiv.org/pdf/1203.5483.pdf) and [YLZ13](http://arxiv.org/pdf/1311.5750.pdf).
- [ ] extend IHT to other nonlinear settings, if possible
- [ ] carefullly analyze the allocations of CPU/GPU resources when using PLINK.jl. The GPU code for GWAs analysis mysteriously collapses whenever two GPUs are used.
